### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by drmenzelit** [lal12/nextcloud-joomla-auth#1]
Hi,
it is also possible the other way around? To export Joomla users and import them in Nextcloud and to login into Nextcloud with the Joomla credentials?

Regards,
Viviana

**Comment by lal12** [comment]
No it is not. 
That would either require writing a plugin for nextcloud or creating a plugin for joomla which updates the nextcloud database on every change.

**Comment by drmenzelit** [comment]
Thanks :-)
