### ISSUE TITLE
Question ..

### ISSUE THREAD

**Issue by thsfo** [lal12/nextcloud-joomla-auth#2]
Hello,

I'm not understant how this plugin work. 
- First i created all my user in NextCloud. 
- and I installed your plugin in joomla... and ?

(if it's work i can send to you french traduction if you want)

**Comment by lal12** [comment]
Hello thsfo,

> I'm not understant how this plugin work.

you have to configure the plugin in the settings. I just updated the README and added a short tutorial on how to install and configure it, so look there for further instructions.

> (if it's work i can send to you french traduction if you want)

I guess you mean "translation"? I do not think it is indispensable, but feel free to create a pull request, then I will add it.

**Comment by thsfo** [comment]
Thanks for your answer.

When i tried to connect in joomla with a nextcloud credentials it doesn't work..  what it means "from the specified Owncloud / Nextcloud Server."
