### ISSUE TITLE
joomla, nextcloud, ldap

### ISSUE THREAD

**Issue by carlang59** [lal12/nextcloud-joomla-auth#3]
hi, I have a joomla site and one with nextcloud 12. and ldap authentication is enabled for both. This plugin allows users to switch from joomla to nextcloud without re-logging in?
Thanks for the reply.
Carlo

**Comment by poVoq** [comment]
AFAIK, no. If you already have it working with LDAP no need for this.

However if your Joomla is on a different server and you don't want to expose your LDAP publicly, this Joomla plugin will probably work if I understood right (still need to test it myself).

**Comment by lal12** [comment]
As @poVoq already said this only enables you to log into joomla as a nextcloud user. Whether nextcloud maintaines its own users or uses LDAP as a backend does not matter.

@carlang59 To be able to have seamless login (SSO) is not that easy task, at least if you have nextcloud an joomla on different domains. For that you should look into SSO, SAML and OAuth.
