### ISSUE TITLE
Love the concept, how to implement?

### ISSUE THREAD

**Issue by CSchaefer70** [lal12/nextcloud-joomla-auth#5]
I'm using both NextCloud (12.0.5) and Joomla! 3.8.5.  I installed your plugin into the Joomla.  Both sites are on the same server with SSL. [https://gbranlaw.com/stage2018/index.php] and [https://gbranlaw.com/nxtcld2018/index.php/login].

So how do I use this to facilitate user login... my expectation is that the user los in ONCE and the hook would complete login for the other within a wrapper or link on the one of the URl locations???

Please clarify usage... thank you so much for your interest and efforts!

**Comment by lal12** [comment]
I am not exactly sure what you mean, but as far as I understand it, you want a single sign on. I already answered a question relating SSO in #3.
